<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<body style="background-color:powderblue;"
<form action ="include/ formhandler.php" mthod = "post">
    <label for = "firstname"> firstname </lable><br>
<input id= "firstname" type ="text " placeholder = firstname ><br>
    <label for ="lastname"> firstname </lable><br>
    <input id = "lastnmae" type ="text" placeholder ="lastname "><br>
    <label Email>Email<label><br>
    <input id="Email"  type ="Email" placeholder="Email"> <br>
    <label password> password<label><br>
    <input id="Password" type ="Password" placeholder="Password"> <br>
    <!-- <label for hubbies>hubbies </label> -->
<!-- <select id = "hubbies" name = "hubbies">
<option value = "sporting">porting</option>
<option value = "movies">movies</option>
<option value = "singing">singing </option>
</select><br><p> -->
 <button type ="submit"> <a href="formhandler.php"></a>Sign up </button> 
<?php 
?>
</body>
</html>